# Generated by Django 3.2 on 2021-05-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipanampesaonlinepayment',
            name='checkout_request_Id',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='mpesadetails',
            name='site_url',
            field=models.URLField(help_text="enter your site full url without '/' at the end. Example: https://mysite.com"),
        ),
    ]
